parameters:
    catrobat.api.controller.search.class: Catrobat\ApiBundle\Controller\SearchController
    catrobat.api.controller.upload.class: Catrobat\ApiBundle\Controller\UploadController
    catrobat.api.controller.security.class: Catrobat\ApiBundle\Controller\SecurityController
    catrobat.api.controller.listprograms.class: Catrobat\ApiBundle\Controller\ListProgramsController
    catrobat.api.controller.download.class: Catrobat\ApiBundle\Controller\DownloadProgramController

services:
    catrobat.api.controller.search:
        class: "%catrobat.api.controller.search.class%"
        arguments: ["@catrobat.core.model.programmanager", "@catrobat.core.services.elapsed.time"]

    catrobat.api.controller.listprograms:
        class: "%catrobat.api.controller.listprograms.class%"
        arguments: ["@catrobat.core.model.programmanager", "@catrobat.core.services.screenshot.repository", "@catrobat.core.services.elapsed.time"]

    catrobat.api.controller.listmostdownloadedprograms:
        class: "%catrobat.api.controller.listprograms.class%"
        arguments: ["@catrobat.core.model.programmanager"]

    catrobat.api.controller.listmostviewedprograms:
        class: "%catrobat.api.controller.listprograms.class%"
        arguments: ["@catrobat.core.model.programmanager"]

    catrobat.api.controller.security:
        class: "%catrobat.api.controller.security.class%"
        arguments: ["@catrobat.core.model.usermanager", "@catrobat.core.services.tokengenerator","@validator", "@translator"]
        
    catrobat.api.controller.upload:
        class: "%catrobat.api.controller.upload.class%"
        arguments: ["@catrobat.core.model.usermanager", "@security.context", "@catrobat.core.model.programmanager", "@catrobat.core.services.tokengenerator","@translator"]

    catrobat.api.controller.download:
        class: "%catrobat.api.controller.download.class%"
        arguments: ["@catrobat.core.model.programmanager","@catrobat.core.services.file.repository"]
        
    uploadtoken.security.authentication.provider:
        class:  Catrobat\ApiBundle\Security\UploadTokenAuthenticationProvider
        arguments: [""]

    uploadtoken.security.authentication.listener:
        class:  Catrobat\ApiBundle\Security\UploadTokenListener
        arguments: ["@security.context", "@security.authentication.manager","", "@translator"]
